-- PAX CRM parametre altyapisi
-- Amaç: hard-code edilen liste/degerleri DB'den yönetilebilir hale getirmek.
-- Admin/Super Admin Parametre Yönetimi ekranı bu tabloyu kullanır.

create table if not exists public.system_parameters (
  id uuid primary key default gen_random_uuid(),
  group_key text not null,
  param_key text not null,
  label text not null,
  value text not null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (group_key, param_key)
);

create index if not exists idx_system_parameters_group_active_sort
  on public.system_parameters (group_key, is_active, sort_order, label);

insert into public.system_parameters (group_key, param_key, label, value, sort_order, meta)
values
  ('activity_status', 'baslamadi', 'Başlamadı', 'Başlamadı', 10, '{"source":"seed"}'::jsonb),
  ('activity_status', 'bekleniyor', 'Bekleniyor', 'Bekleniyor', 20, '{"source":"seed"}'::jsonb),
  ('activity_status', 'devam_ediyor', 'Devam Ediyor', 'Devam Ediyor', 30, '{"source":"seed"}'::jsonb),
  ('activity_status', 'tamamlandi', 'Tamamlandı', 'Tamamlandı', 40, '{"source":"seed"}'::jsonb),
  ('activity_status', 'ihtiyac_duyulmadi', 'İhtiyaç Duyulmadı', 'İhtiyaç Duyulmadı', 50, '{"source":"seed"}'::jsonb),
  ('integration_type', 'a2a', 'A2A', 'A2A', 10, '{"source":"seed"}'::jsonb),
  ('integration_type', 'd2d', 'D2D', 'D2D', 20, '{"source":"seed"}'::jsonb),
  ('integration_type', 'd2d_a2a', 'D2D+A2A', 'D2D+A2A', 30, '{"source":"seed"}'::jsonb),
  ('sales_probability', 'dusuk', 'Düşük', 'Düşük', 10, '{"source":"seed"}'::jsonb),
  ('sales_probability', 'orta', 'Orta', 'Orta', 20, '{"source":"seed"}'::jsonb),
  ('sales_probability', 'yuksek', 'Yüksek', 'Yüksek', 30, '{"source":"seed"}'::jsonb),

  ('kunye_magaza_sayisi', '1_25', '1-25', '1-25', 10, '{"source":"seed"}'::jsonb),
  ('kunye_magaza_sayisi', '26_200', '26-200', '26-200', 20, '{"source":"seed"}'::jsonb),
  ('kunye_magaza_sayisi', '201_500', '201-500', '201-500', 30, '{"source":"seed"}'::jsonb),
  ('kunye_magaza_sayisi', '500', '500+', '500+', 40, '{"source":"seed"}'::jsonb),
  ('kunye_franchise_sayisi', 'yok', 'Yok', 'Yok', 10, '{"source":"seed"}'::jsonb),
  ('kunye_franchise_sayisi', '1_25', '1-25', '1-25', 20, '{"source":"seed"}'::jsonb),
  ('kunye_franchise_sayisi', '26_200', '26-200', '26-200', 30, '{"source":"seed"}'::jsonb),
  ('kunye_franchise_sayisi', '201_500', '201-500', '201-500', 40, '{"source":"seed"}'::jsonb),
  ('kunye_franchise_sayisi', '500', '500+', '500+', 50, '{"source":"seed"}'::jsonb),
  ('kunye_sabit_kasa_adedi', 'kullanilmiyor', 'Kullanılmıyor', 'Kullanılmıyor', 10, '{"source":"seed"}'::jsonb),
  ('kunye_sabit_kasa_adedi', '1_25', '1-25', '1-25', 20, '{"source":"seed"}'::jsonb),
  ('kunye_sabit_kasa_adedi', '26_200', '26-200', '26-200', 30, '{"source":"seed"}'::jsonb),
  ('kunye_sabit_kasa_adedi', '201_500', '201-500', '201-500', 40, '{"source":"seed"}'::jsonb),
  ('kunye_sabit_kasa_adedi', '500', '500+', '500+', 50, '{"source":"seed"}'::jsonb),

  ('kunye_kasapos_firmasi', 'nebim', 'Nebim', 'Nebim', 10, '{"source":"seed"}'::jsonb),
  ('kunye_kasapos_firmasi', 'toshiba', 'Toshiba', 'Toshiba', 20, '{"source":"seed"}'::jsonb),
  ('kunye_kasapos_firmasi', 'echopos', 'Echopos', 'Echopos', 30, '{"source":"seed"}'::jsonb),
  ('kunye_kasapos_firmasi', 'ncr', 'NCR', 'NCR', 40, '{"source":"seed"}'::jsonb),
  ('kunye_kasapos_firmasi', 'encore', 'Encore', 'Encore', 50, '{"source":"seed"}'::jsonb),
  ('kunye_kasapos_firmasi', 'enpos', 'Enpos', 'Enpos', 60, '{"source":"seed"}'::jsonb),
  ('kunye_kasapos_firmasi', 'logo', 'Logo', 'Logo', 70, '{"source":"seed"}'::jsonb),
  ('kunye_kasapos_firmasi', 'posback', 'Posback', 'Posback', 80, '{"source":"seed"}'::jsonb),
  ('kunye_kasapos_firmasi', 'smartpos', 'Smartpos', 'Smartpos', 90, '{"source":"seed"}'::jsonb),
  ('kunye_kasapos_firmasi', 'barsoft', 'Barsoft', 'Barsoft', 100, '{"source":"seed"}'::jsonb),
  ('kunye_kasapos_firmasi', 'protel', 'Protel', 'Protel', 110, '{"source":"seed"}'::jsonb),
  ('kunye_kasapos_firmasi', 'avion', 'Avion', 'Avion', 120, '{"source":"seed"}'::jsonb),
  ('kunye_kasapos_firmasi', 'inhouse', 'Inhouse', 'Inhouse', 130, '{"source":"seed"}'::jsonb),
  ('kunye_kasapos_firmasi', 'denpos', 'Denpos', 'Denpos', 140, '{"source":"seed"}'::jsonb),
  ('kunye_kasapos_firmasi', 'diger', 'Diğer', 'Diğer', 999, '{"source":"seed"}'::jsonb),

  ('kunye_pos_modeli', 'okc', 'ÖKC', 'ÖKC', 10, '{"source":"seed"}'::jsonb),
  ('kunye_pos_modeli', 'eft', 'EFT', 'EFT', 20, '{"source":"seed"}'::jsonb),
  ('kunye_pos_markasi', 'ingenico', 'Ingenico', 'Ingenico', 10, '{"source":"seed"}'::jsonb),
  ('kunye_pos_markasi', 'verifone', 'Verifone', 'Verifone', 20, '{"source":"seed"}'::jsonb),
  ('kunye_pos_markasi', 'pax', 'PAX', 'PAX', 30, '{"source":"seed"}'::jsonb),
  ('kunye_pos_markasi', 'pavo', 'Pavo', 'Pavo', 40, '{"source":"seed"}'::jsonb),
  ('kunye_pos_markasi', 'hugin', 'Hugin', 'Hugin', 50, '{"source":"seed"}'::jsonb),
  ('kunye_pos_markasi', 'sunmi', 'Sunmi', 'Sunmi', 60, '{"source":"seed"}'::jsonb),
  ('kunye_pos_markasi', 'profilo', 'Profilo', 'Profilo', 70, '{"source":"seed"}'::jsonb),
  ('kunye_pos_markasi', 'beko', 'Beko', 'Beko', 80, '{"source":"seed"}'::jsonb),
  ('kunye_pos_markasi', 'vera', 'Vera', 'Vera', 90, '{"source":"seed"}'::jsonb),
  ('kunye_pos_markasi', 'inpos', 'Inpos', 'Inpos', 100, '{"source":"seed"}'::jsonb),
  ('kunye_pos_markasi', 'diger', 'Diğer', 'Diğer', 999, '{"source":"seed"}'::jsonb),

  ('kunye_alim_yili', '1_yildan_az', '1 yıldan az', '1 yıldan az', 10, '{"source":"seed"}'::jsonb),
  ('kunye_alim_yili', '1_3_yil', '1-3 yıl', '1-3 yıl', 20, '{"source":"seed"}'::jsonb),
  ('kunye_alim_yili', '3_5_yil', '3-5 yıl', '3-5 yıl', 30, '{"source":"seed"}'::jsonb),
  ('kunye_alim_yili', '5_yil', '5+ yıl', '5+ yıl', 40, '{"source":"seed"}'::jsonb),

  ('kunye_bilgisayar_markasi', 'hp', 'HP', 'HP', 10, '{"source":"seed"}'::jsonb),
  ('kunye_bilgisayar_markasi', 'posback', 'Posback', 'Posback', 20, '{"source":"seed"}'::jsonb),
  ('kunye_bilgisayar_markasi', 'echopos', 'Echopos', 'Echopos', 30, '{"source":"seed"}'::jsonb),
  ('kunye_bilgisayar_markasi', 'toshiba', 'Toshiba', 'Toshiba', 40, '{"source":"seed"}'::jsonb),
  ('kunye_bilgisayar_markasi', 'enpos', 'Enpos', 'Enpos', 50, '{"source":"seed"}'::jsonb),
  ('kunye_bilgisayar_markasi', 'ncr', 'NCR', 'NCR', 60, '{"source":"seed"}'::jsonb),
  ('kunye_bilgisayar_markasi', 'encore', 'Encore', 'Encore', 70, '{"source":"seed"}'::jsonb),
  ('kunye_bilgisayar_markasi', 'dn', 'D&N', 'D&N', 80, '{"source":"seed"}'::jsonb),
  ('kunye_bilgisayar_markasi', 'oem', 'OEM', 'OEM', 90, '{"source":"seed"}'::jsonb),
  ('kunye_bilgisayar_markasi', 'diger', 'Diğer', 'Diğer', 999, '{"source":"seed"}'::jsonb),

  ('kunye_evet_hayir', 'hayir', 'Hayır', 'Hayır', 10, '{"source":"seed"}'::jsonb),
  ('kunye_evet_hayir', 'evet', 'Evet', 'Evet', 20, '{"source":"seed"}'::jsonb),
  ('kunye_odeme_yazilimi', 'logo', 'Logo', 'Logo', 10, '{"source":"seed"}'::jsonb),
  ('kunye_odeme_yazilimi', 'nebim', 'Nebim', 'Nebim', 20, '{"source":"seed"}'::jsonb),
  ('kunye_odeme_yazilimi', 'genius', 'Genius', 'Genius', 30, '{"source":"seed"}'::jsonb),
  ('kunye_odeme_yazilimi', 'ncr', 'NCR', 'NCR', 40, '{"source":"seed"}'::jsonb),
  ('kunye_odeme_yazilimi', 'tera', 'Tera', 'Tera', 50, '{"source":"seed"}'::jsonb),
  ('kunye_odeme_yazilimi', 'enpos', 'Enpos', 'Enpos', 60, '{"source":"seed"}'::jsonb),
  ('kunye_odeme_yazilimi', 'in_house', 'In House', 'In House', 70, '{"source":"seed"}'::jsonb),
  ('kunye_odeme_yazilimi', 'diger', 'Diğer', 'Diğer', 999, '{"source":"seed"}'::jsonb),

  ('kunye_reyon_cihaz_modeli', 'zebra', 'Zebra', 'Zebra', 10, '{"source":"seed"}'::jsonb),
  ('kunye_reyon_cihaz_modeli', 'honeywell', 'Honeywell', 'Honeywell', 20, '{"source":"seed"}'::jsonb),
  ('kunye_reyon_cihaz_modeli', 'datalogic', 'Datalogic', 'Datalogic', 30, '{"source":"seed"}'::jsonb),
  ('kunye_reyon_cihaz_modeli', 'newland', 'Newland', 'Newland', 40, '{"source":"seed"}'::jsonb),
  ('kunye_reyon_cihaz_modeli', 'sunmi', 'Sunmi', 'Sunmi', 50, '{"source":"seed"}'::jsonb),
  ('kunye_reyon_cihaz_modeli', 'pax', 'PAX', 'PAX', 60, '{"source":"seed"}'::jsonb),
  ('kunye_reyon_cihaz_modeli', 'diger', 'Diğer', 'Diğer', 999, '{"source":"seed"}'::jsonb),

  ('kunye_el_terminali_modeli', 'honeywell', 'Honeywell', 'Honeywell', 10, '{"source":"seed"}'::jsonb),
  ('kunye_el_terminali_modeli', 'idata', 'iData', 'iData', 20, '{"source":"seed"}'::jsonb),
  ('kunye_el_terminali_modeli', 'disc', 'Disc', 'Disc', 30, '{"source":"seed"}'::jsonb),
  ('kunye_el_terminali_modeli', 'zebra', 'Zebra', 'Zebra', 40, '{"source":"seed"}'::jsonb),
  ('kunye_el_terminali_modeli', 'newland', 'Newland', 'Newland', 50, '{"source":"seed"}'::jsonb),
  ('kunye_el_terminali_modeli', 'point_mobile', 'Point Mobile', 'Point Mobile', 60, '{"source":"seed"}'::jsonb),
  ('kunye_el_terminali_modeli', 'urovo', 'Urovo', 'Urovo', 70, '{"source":"seed"}'::jsonb),
  ('kunye_el_terminali_modeli', 'telefon', 'Telefon', 'Telefon', 80, '{"source":"seed"}'::jsonb),
  ('kunye_el_terminali_modeli', 'diger', 'Diğer', 'Diğer', 999, '{"source":"seed"}'::jsonb),

  ('kunye_erp', 'logo', 'Logo', 'Logo', 10, '{"source":"seed"}'::jsonb),
  ('kunye_erp', 'nebim', 'Nebim', 'Nebim', 20, '{"source":"seed"}'::jsonb),
  ('kunye_erp', 'genius', 'Genius', 'Genius', 30, '{"source":"seed"}'::jsonb),
  ('kunye_erp', 'ncr', 'NCR', 'NCR', 40, '{"source":"seed"}'::jsonb),
  ('kunye_erp', 'tera', 'Tera', 'Tera', 50, '{"source":"seed"}'::jsonb),
  ('kunye_erp', 'enpos', 'Enpos', 'Enpos', 60, '{"source":"seed"}'::jsonb),
  ('kunye_erp', 'mikro', 'Mikro', 'Mikro', 70, '{"source":"seed"}'::jsonb),
  ('kunye_erp', 'posback', 'Posback', 'Posback', 80, '{"source":"seed"}'::jsonb),
  ('kunye_erp', 'sap', 'SAP', 'SAP', 90, '{"source":"seed"}'::jsonb),
  ('kunye_erp', 'axapta', 'AXAPTA', 'AXAPTA', 100, '{"source":"seed"}'::jsonb),
  ('kunye_erp', 'oracle', 'Oracle', 'Oracle', 110, '{"source":"seed"}'::jsonb),
  ('kunye_erp', 'uyumsoft', 'Uyumsoft', 'Uyumsoft', 120, '{"source":"seed"}'::jsonb),
  ('kunye_erp', 'giz', 'Giz', 'Giz', 130, '{"source":"seed"}'::jsonb),
  ('kunye_erp', 'in_house', 'In House', 'In House', 140, '{"source":"seed"}'::jsonb),
  ('kunye_erp', 'diger', 'Diğer', 'Diğer', 999, '{"source":"seed"}'::jsonb),

  ('kunye_banka', 'akbank', 'Akbank', 'Akbank', 10, '{"source":"seed"}'::jsonb),
  ('kunye_banka', 'garanti_bbva', 'Garanti BBVA', 'Garanti BBVA', 20, '{"source":"seed"}'::jsonb),
  ('kunye_banka', 'is_bankasi', 'İş Bankası', 'İş Bankası', 30, '{"source":"seed"}'::jsonb),
  ('kunye_banka', 'yapi_kredi', 'Yapı Kredi', 'Yapı Kredi', 40, '{"source":"seed"}'::jsonb),
  ('kunye_banka', 'halkbank', 'Halkbank', 'Halkbank', 50, '{"source":"seed"}'::jsonb),
  ('kunye_banka', 'vakifbank', 'VakıfBank', 'VakıfBank', 60, '{"source":"seed"}'::jsonb),
  ('kunye_banka', 'ziraat_bankasi', 'Ziraat Bankası', 'Ziraat Bankası', 70, '{"source":"seed"}'::jsonb),
  ('kunye_banka', 'qnb', 'QNB', 'QNB', 80, '{"source":"seed"}'::jsonb),
  ('kunye_banka', 'teb', 'TEB', 'TEB', 90, '{"source":"seed"}'::jsonb),
  ('kunye_banka', 'denizbank', 'DenizBank', 'DenizBank', 100, '{"source":"seed"}'::jsonb),
  ('kunye_banka', 'aktifbank', 'AktifBank', 'AktifBank', 110, '{"source":"seed"}'::jsonb),

  ('kunye_pos_mulkiyet', 'kendisi', 'Kendisi', 'Kendisi', 10, '{"source":"seed"}'::jsonb),
  ('kunye_pos_mulkiyet', 'banka', 'Banka', 'Banka', 20, '{"source":"seed"}'::jsonb),
  ('kunye_pos_mulkiyet', 'bankada', 'Bankada', 'Bankada', 30, '{"source":"seed"}'::jsonb),
  ('kunye_saha_hizmeti_firmasi', 'bilinmiyor', 'Bilinmiyor', 'Bilinmiyor', 10, '{"source":"seed"}'::jsonb),
  ('kunye_saha_hizmeti_firmasi', 'teknoser', 'Teknoser', 'Teknoser', 20, '{"source":"seed"}'::jsonb),
  ('kunye_saha_hizmeti_firmasi', 'ibm', 'IBM', 'IBM', 30, '{"source":"seed"}'::jsonb),
  ('kunye_saha_hizmeti_firmasi', 'payser', 'Payser', 'Payser', 40, '{"source":"seed"}'::jsonb),
  ('kunye_saha_hizmeti_firmasi', 'diger', 'Diğer', 'Diğer', 999, '{"source":"seed"}'::jsonb),
  ('kunye_memnuniyet', 'memnun', 'Memnun', 'Memnun', 10, '{"source":"seed"}'::jsonb),
  ('kunye_memnuniyet', 'orta', 'Orta', 'Orta', 20, '{"source":"seed"}'::jsonb),
  ('kunye_memnuniyet', 'memnun_degil', 'Memnun Değil', 'Memnun Değil', 30, '{"source":"seed"}'::jsonb)
on conflict (group_key, param_key) do nothing;


-- Sistem davranış parametreleri: tekrar çalıştırıldığında mevcut kayıtları değiştirmez.
insert into public.system_parameters (group_key, param_key, label, value, sort_order, meta)
values
  ('system_jira_enabled', 'aktif', 'Aktif', 'true', 10, '{"source":"seed","module":"Sistem Davranışları","category":"Jira"}'::jsonb),
  ('system_jira_weekly_pptx_enabled', 'aktif', 'Aktif', 'true', 10, '{"source":"seed","module":"Sistem Davranışları","category":"Jira"}'::jsonb),
  ('system_jira_debug_enabled', 'aktif', 'Aktif', 'true', 10, '{"source":"seed","module":"Sistem Davranışları","category":"Jira"}'::jsonb),
  ('system_pptx_download_enabled', 'aktif', 'Aktif', 'true', 10, '{"source":"seed","module":"Sistem Davranışları","category":"Rapor / PPTX"}'::jsonb),
  ('system_page_size', '25', '25', '25', 10, '{"source":"seed","module":"Sistem Davranışları","category":"Performans"}'::jsonb)
on conflict (group_key, param_key) do nothing;
